### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by Descent098** [Descent098/ezcv#3]
## Page Fields
- [x] Created
- [x] Updated
- [x] Title (used for URL)
- [ ] Featured
- [ ] image
- [x] Heading
- [ ] Tagline
- [x] Content

## TODO

- [x] Create a custom parsing method for content sections called "blog"
- [x] Create a theme schema that allows "overview", "single", and "feed" (overview with only 1 page) templates for each

## Schemas
Below are the purposed schemas for the blog section.

### Theme Schema

```
📁<theme_name>/
├── 📁css/
|   └──📄 <file_name>.css
├── 📁js/
|   └──📄 <file_name>.js
├── 📁images/
|   └──📄 <file_name>.<extension>
├── 📁sections/
|   └── 📁blog/
|            ├── 📄 overview.jinja
|            ├──📄 single.jinja
|            └── 📄 feed.jinja
|   └──📄 <section_name>.jinja
└── 📄index.jinja
```

### Content Schema

```
├── 📁content/
│   ├── 📁blog/
│   |   └── 📝<filename>.md
```

## Additional Steps

- [x] Document creating content for blogs
- [x] Document creating themes for blogs

## Themes
- [x] Dimension
- [x] Grayscale
- [x] solid_state
- [x] read_only
