### ISSUE TITLE
Add section command

### ISSUE THREAD

**Issue by Descent098** [Descent098/ezcv#40]
Add new CLI command

`ezcv section -n <SECTION_NAME> [-t=<type>]`

## Steps

1. Check if theme is in project folder, if not copy to the folder
2. Generate current metadata if file is not available
3. Copy current metadata info
4. Create new files
5. ~Insert new section information and resave metadata (including fields where available)~ (not possible)

## Type specification

Options:
- `m` or `markdown`: generate standard markdown section
- `b` or `blog`: Generate a blog
  - Append an `o` (overview), `s` (single), `f` (feed) for which you want to generate  or don't include any to generate all 
  - check if type starts with a b, then strip literal "blog" and "b", then check for "o", "s", "f" for indications on blog sections
  - Set default "fields" to ["title", "created", "updated"]
- `g` or `gallery`: generate a gallery

## TODO

- [x] Implement command for creating new sections
- [x] Update docstrings
- [x] Update command so section info prints if section already exists
  - [x] Update readme and CLI docs once completed

## Docs

- [x] Readme
- [x] CLI docs
