### ISSUE TITLE
Theme Evie 

### ISSUE THREAD

**Issue by Descent098** [Descent098/ezcv#42]
name: evie
URL: https://onepagelove.com/evie

## TODO

- [x] Create theme
    - [x] Create `index.jijna`
    - [x] Add in CSS/JS
    - [x] Create sections
    - [x] Create metadata
      - [x] Add in `required: true` to fields that need it
      - [x] Add in required_config
- [x] Add documentation to `docs/included-themes.md`
- [x] Add to `remotes.yml`
